import React, { useEffect, useRef, useState } from 'react';
import html2canvas from 'html2canvas';
import { calculateCartTotals, formatFulfillmentSummary } from '../lib/cart-calculations';
import FortniteItemImage from './FortniteItemImage';

export default function OrderReceiptGenerator({ order, onGenerated }) {
  const ref = useRef(null);
  const [error, setError] = useState('');
  const calculations = order.calculations || calculateCartTotals(order.items);
  useEffect(() => { html2canvas(ref.current, { scale: 2, backgroundColor: '#0b0812', logging: false, useCORS: true, allowTaint: false }).then((canvas) => onGenerated(canvas.toDataURL('image/png'))).catch(() => setError('No se pudo generar la imagen local. Intenta de nuevo.')); }, [onGenerated]);
  return <>{error && <p role="alert" className="text-red-200">{error}</p>}<div ref={ref} className="fixed -left-[9999px] top-0 w-[900px] bg-[#0b0812] p-12 font-sans text-white"><h1 className="text-5xl font-black text-purple-300">KTXStore</h1><p className="mt-2 text-xl text-cyan-300">Pedido {order.id}</p><p className="text-slate-400">{order.date} · {order.country.name}</p><div className="mt-8 rounded-2xl bg-[#171222] p-6"><h2 className="text-2xl font-bold">{order.game.name}</h2>{calculations.lines.map(({ product, quantity, fulfillmentTotal, fulfillmentLabel, subtotal }) => <div key={product.id} className="mt-4 flex gap-4"><div className="w-20 shrink-0">{product.gameId === 'fortnite' && <FortniteItemImage item={product} category={product.category} forCanvas />}</div><div><p>{quantity} × {product.name}</p><p className="text-slate-300">Entrega: {fulfillmentTotal === null ? 'Cantidad por confirmar' : `${fulfillmentTotal} ${fulfillmentLabel}`} · Subtotal: {product.price === null ? 'Precio por definir' : `S/ ${subtotal.toFixed(2)}`}</p></div></div>)}<div className="mt-6 border-t border-white/10 pt-4"><p>Unidades seleccionadas: {calculations.totalUnits}</p><p>Total a recibir: {formatFulfillmentSummary(calculations)}</p><p className="mt-2 text-3xl font-black text-cyan-300">Total a pagar: S/ {calculations.totalMoney.toFixed(2)}</p></div></div><div className="mt-6 rounded-2xl bg-[#171222] p-6"><p>Nombre: {order.form.name}</p><p>Contacto: {order.form.contact}</p>{order.form.identifier && <p>Identificador: {order.form.identifier.replace(/.(?=.{3})/g, '*')}</p>}<p>Método: {order.paymentMethod}</p><p className="mt-4 font-bold text-amber-300">Estado: Pendiente de verificación</p>{order.testOnly && <p className="mt-3 font-black text-red-300">PRUEBA — NO PAGAR</p>}</div><p className="mt-8 text-lg text-slate-300">Envía esta imagen y tu comprobante a KTXStore para procesar tu pedido.</p></div></>;
}
